volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}



services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: flix_local_django
    container_name: local_django
    depends_on:
      - postgres
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.env
    ports:
      - '8000:8000'
    command: /start.sh

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: flix_production_postgres
    container_name: local_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    ports:
      - "5432:5432"
    env_file:
      - ./.envs/.local/.env
